# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sergei/Projects/ProgressBar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sergei/Projects/ProgressBar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergei/Projects/ProgressBar/CMakeFiles /home/sergei/Projects/ProgressBar//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sergei/Projects/ProgressBar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PBar

# Build rule for target.
PBar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PBar
.PHONY : PBar

# fast build rule for target.
PBar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PBar.dir/build.make CMakeFiles/PBar.dir/build
.PHONY : PBar/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named style

# Build rule for target.
style: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 style
.PHONY : style

# fast build rule for target.
style/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/style.dir/build.make CMakeFiles/style.dir/build
.PHONY : style/fast

#=============================================================================
# Target rules for targets named possibilities

# Build rule for target.
possibilities: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 possibilities
.PHONY : possibilities

# fast build rule for target.
possibilities/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/possibilities.dir/build.make CMakeFiles/possibilities.dir/build
.PHONY : possibilities/fast

#=============================================================================
# Target rules for targets named speed

# Build rule for target.
speed: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 speed
.PHONY : speed

# fast build rule for target.
speed/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/speed.dir/build.make CMakeFiles/speed.dir/build
.PHONY : speed/fast

#=============================================================================
# Target rules for targets named handle_output

# Build rule for target.
handle_output: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 handle_output
.PHONY : handle_output

# fast build rule for target.
handle_output/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/handle_output.dir/build.make CMakeFiles/handle_output.dir/build
.PHONY : handle_output/fast

#=============================================================================
# Target rules for targets named mt

# Build rule for target.
mt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mt
.PHONY : mt

# fast build rule for target.
mt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/build
.PHONY : mt/fast

examples/handle_output.o: examples/handle_output.cpp.o
.PHONY : examples/handle_output.o

# target to build an object file
examples/handle_output.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/handle_output.dir/build.make CMakeFiles/handle_output.dir/examples/handle_output.cpp.o
.PHONY : examples/handle_output.cpp.o

examples/handle_output.i: examples/handle_output.cpp.i
.PHONY : examples/handle_output.i

# target to preprocess a source file
examples/handle_output.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/handle_output.dir/build.make CMakeFiles/handle_output.dir/examples/handle_output.cpp.i
.PHONY : examples/handle_output.cpp.i

examples/handle_output.s: examples/handle_output.cpp.s
.PHONY : examples/handle_output.s

# target to generate assembly for a file
examples/handle_output.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/handle_output.dir/build.make CMakeFiles/handle_output.dir/examples/handle_output.cpp.s
.PHONY : examples/handle_output.cpp.s

examples/mt.o: examples/mt.cpp.o
.PHONY : examples/mt.o

# target to build an object file
examples/mt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/examples/mt.cpp.o
.PHONY : examples/mt.cpp.o

examples/mt.i: examples/mt.cpp.i
.PHONY : examples/mt.i

# target to preprocess a source file
examples/mt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/examples/mt.cpp.i
.PHONY : examples/mt.cpp.i

examples/mt.s: examples/mt.cpp.s
.PHONY : examples/mt.s

# target to generate assembly for a file
examples/mt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mt.dir/build.make CMakeFiles/mt.dir/examples/mt.cpp.s
.PHONY : examples/mt.cpp.s

examples/possibilities.o: examples/possibilities.cpp.o
.PHONY : examples/possibilities.o

# target to build an object file
examples/possibilities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/possibilities.dir/build.make CMakeFiles/possibilities.dir/examples/possibilities.cpp.o
.PHONY : examples/possibilities.cpp.o

examples/possibilities.i: examples/possibilities.cpp.i
.PHONY : examples/possibilities.i

# target to preprocess a source file
examples/possibilities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/possibilities.dir/build.make CMakeFiles/possibilities.dir/examples/possibilities.cpp.i
.PHONY : examples/possibilities.cpp.i

examples/possibilities.s: examples/possibilities.cpp.s
.PHONY : examples/possibilities.s

# target to generate assembly for a file
examples/possibilities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/possibilities.dir/build.make CMakeFiles/possibilities.dir/examples/possibilities.cpp.s
.PHONY : examples/possibilities.cpp.s

examples/speed.o: examples/speed.cpp.o
.PHONY : examples/speed.o

# target to build an object file
examples/speed.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/speed.dir/build.make CMakeFiles/speed.dir/examples/speed.cpp.o
.PHONY : examples/speed.cpp.o

examples/speed.i: examples/speed.cpp.i
.PHONY : examples/speed.i

# target to preprocess a source file
examples/speed.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/speed.dir/build.make CMakeFiles/speed.dir/examples/speed.cpp.i
.PHONY : examples/speed.cpp.i

examples/speed.s: examples/speed.cpp.s
.PHONY : examples/speed.s

# target to generate assembly for a file
examples/speed.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/speed.dir/build.make CMakeFiles/speed.dir/examples/speed.cpp.s
.PHONY : examples/speed.cpp.s

examples/style.o: examples/style.cpp.o
.PHONY : examples/style.o

# target to build an object file
examples/style.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/style.dir/build.make CMakeFiles/style.dir/examples/style.cpp.o
.PHONY : examples/style.cpp.o

examples/style.i: examples/style.cpp.i
.PHONY : examples/style.i

# target to preprocess a source file
examples/style.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/style.dir/build.make CMakeFiles/style.dir/examples/style.cpp.i
.PHONY : examples/style.cpp.i

examples/style.s: examples/style.cpp.s
.PHONY : examples/style.s

# target to generate assembly for a file
examples/style.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/style.dir/build.make CMakeFiles/style.dir/examples/style.cpp.s
.PHONY : examples/style.cpp.s

examples/test.o: examples/test.cpp.o
.PHONY : examples/test.o

# target to build an object file
examples/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/examples/test.cpp.o
.PHONY : examples/test.cpp.o

examples/test.i: examples/test.cpp.i
.PHONY : examples/test.i

# target to preprocess a source file
examples/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/examples/test.cpp.i
.PHONY : examples/test.cpp.i

examples/test.s: examples/test.cpp.s
.PHONY : examples/test.s

# target to generate assembly for a file
examples/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/examples/test.cpp.s
.PHONY : examples/test.cpp.s

src/PBar.o: src/PBar.cpp.o
.PHONY : src/PBar.o

# target to build an object file
src/PBar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PBar.dir/build.make CMakeFiles/PBar.dir/src/PBar.cpp.o
.PHONY : src/PBar.cpp.o

src/PBar.i: src/PBar.cpp.i
.PHONY : src/PBar.i

# target to preprocess a source file
src/PBar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PBar.dir/build.make CMakeFiles/PBar.dir/src/PBar.cpp.i
.PHONY : src/PBar.cpp.i

src/PBar.s: src/PBar.cpp.s
.PHONY : src/PBar.s

# target to generate assembly for a file
src/PBar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PBar.dir/build.make CMakeFiles/PBar.dir/src/PBar.cpp.s
.PHONY : src/PBar.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PBar"
	@echo "... handle_output"
	@echo "... mt"
	@echo "... possibilities"
	@echo "... speed"
	@echo "... style"
	@echo "... test"
	@echo "... examples/handle_output.o"
	@echo "... examples/handle_output.i"
	@echo "... examples/handle_output.s"
	@echo "... examples/mt.o"
	@echo "... examples/mt.i"
	@echo "... examples/mt.s"
	@echo "... examples/possibilities.o"
	@echo "... examples/possibilities.i"
	@echo "... examples/possibilities.s"
	@echo "... examples/speed.o"
	@echo "... examples/speed.i"
	@echo "... examples/speed.s"
	@echo "... examples/style.o"
	@echo "... examples/style.i"
	@echo "... examples/style.s"
	@echo "... examples/test.o"
	@echo "... examples/test.i"
	@echo "... examples/test.s"
	@echo "... src/PBar.o"
	@echo "... src/PBar.i"
	@echo "... src/PBar.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

