test: test.cc
	g++ test.cc -Wall -Werror -Wpedantic -o test.exe

style: style.cc
	g++ style.cc -Wall -Werror -Wpedantic -o style.exe

mt: mt.cc
	g++ mt.cc -Wall -Werror -Wpedantic -o mt.exe

speed: speed.cc
	g++ speed.cc -Wall -Werror -Wpedantic -o speed.exe

clean: 
	rm -f \
	test.exe \
	style.exe \
	mt.exe \
	speed.exe
