test: test.cc
	g++ test.cc -Wall -Werror -Wpedantic -o test.exe

test_style: test_style.cc
	g++ test_style.cc -Wall -Werror -Wpedantic -o test_style.exe

test_mt: test_mt.cc
	g++ test_mt.cc -Wall -Werror -Wpedantic -o test_mt.exe

clean: 
	rm -f \
	test.exe\
	test_style.exe\
	test_mt.exe
